# PowerShell script to set up .env file for Trading Stack

Write-Host "Trading Stack Environment Setup" -ForegroundColor Cyan
Write-Host "==============================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if (Test-Path ".env") {
    Write-Host "Found existing .env file" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne 'y' -and $overwrite -ne 'Y') {
        Write-Host "Keeping existing .env file" -ForegroundColor Green
        exit 0
    }
}

Write-Host ""
Write-Host "Please enter your API credentials:" -ForegroundColor Yellow
Write-Host "(Press Enter to skip optional values)" -ForegroundColor Gray
Write-Host ""

# Alpaca credentials
$alpacaKey = Read-Host "Alpaca API Key ID"
$alpacaSecret = Read-Host "Alpaca API Secret Key" -AsSecureString
$alpacaSecretPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($alpacaSecret)
)

# OpenAI (optional)
$openaiKey = Read-Host "OpenAI API Key (optional)"

# IB settings
Write-Host ""
Write-Host "Interactive Brokers settings:" -ForegroundColor Yellow
$ibHost = Read-Host "IB Gateway Host (default: 127.0.0.1)"
if (-not $ibHost) { $ibHost = "127.0.0.1" }

$ibPort = Read-Host "IB Gateway Port (default: 7497)"
if (-not $ibPort) { $ibPort = "7497" }

$ibClientId = Read-Host "IB Client ID (default: 7)"
if (-not $ibClientId) { $ibClientId = "7" }

# Trading environment
Write-Host ""
$execEnv = Read-Host "Trading Environment (paper/live, default: paper)"
if (-not $execEnv) { $execEnv = "paper" }

# Create .env file
$envContent = @"
# Trading Stack Environment Variables
# Generated by setup_env.ps1

# Alpaca API credentials (required for live market data)
ALPACA_API_KEY_ID=$alpacaKey
ALPACA_API_SECRET_KEY=$alpacaSecretPlain

# OpenAI API key (optional, for LLM features)
$(if ($openaiKey) { "OPENAI_API_KEY=$openaiKey" } else { "# OPENAI_API_KEY=your_key_here" })

# Interactive Brokers settings (for live trading)
IB_GATEWAY_HOST=$ibHost
IB_GATEWAY_PORT=$ibPort
IB_CLIENT_ID=$ibClientId

# Trading environment (paper or live)
EXEC_ENV=$execEnv

# Risk management
EQUITY_USD=30000
ACK_P95_MS=1200
"@

# Write to file
$envContent | Out-File -FilePath ".env" -Encoding utf8

Write-Host ""
Write-Host "✓ Created .env file successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Note: .env is already in .gitignore, so your credentials are safe from git" -ForegroundColor Cyan
Write-Host ""
Write-Host "You can now run: .\start_services_with_env.ps1" -ForegroundColor Yellow
